name: example
description: An absolute bare-bones web app.
version: 1.0.0
repository: https://github.com/HenriqueNas/Wed/tree/main/packages/wed_dom/example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  wed_dom:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
