name: wed
description: A web Dart framework, for create declarative UIs.
version: 0.0.1
homepage: www.henriquenas.dev/wed

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.0
  test: ^1.16.0
