name: wed_router_dom
description: routing system for wed_html
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  wed_core:
    path: ../wed_core/

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  
