name: wed_core
description: A web Dart framework, to create declarative UIs.
version: 0.0.1
homepage: https://www.henriquenas.dev/wed
repository: https://github.com/henriquenas/wed
issue_tracker: https://github.com/henriquenas/wed/issues
documentation: https://pub.dev/packages/wed

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^4.0.0+1
