name: wed_core
description: A web Dart framework, to create declarative UIs.
version: 0.0.6
homepage: https://www.henriquenas.dev/wed
repository: https://github.com/henriquenas/wed
issue_tracker: https://github.com/henriquenas/wed/issues
documentation: https://pub.dev/packages/wed


environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  test: ^1.16.0
  very_good_analysis: ^4.0.0+1
